### ISSUE TITLE
fastBMA crashes due to compiler flag

### ISSUE THREAD

**Issue by simonvh** [lhhunghimself/fastBMA#2]
On my system (Intel Xeon E5520, Ubuntu 16.04) fastBMA crashes. This happens both when I compile it, but also when I run the Docker version. Removing the `-mavx` flag seems to fix the problem (the demo runs fine when I remove this flag).

**Comment by lhhunghimself** [comment]
The mavx flag allows for use of avx instructions that are supported in lntel processors ivy bridge and more recent and in later AMD processors. Your Xeon is the older Sandy bridge type. The docker version was compiled with this flag since it's been more than 5 years since the introduction of ivy bridge. Containerization won't help with processor level flags.

**Comment by simonvh** [comment]
I completely understand to focus on more recent generations of processors, but maybe it's possible to mention this in the documentation? The error is otherwise uninformative and it's not that straightforward to track down if you're not familiar with the details of what these compiler flags do. Maybe it will help someone else.

**Comment by lhhunghimself** [comment]
I've updated the documentation to include instructions on the changes needed to run fastBMA on older cpus.

**Comment by simonvh** [comment]
That's great, thanks for the quick response!
